spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC} #change localhost to mysql if inside containers
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:userpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show_sql: false
    generate-ddl: false
    hibernate:
      generate_statistics: false
      ddl-auto: update
    properties:
      hibernate.integration.envers.enabled: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      org.hibernate.envers.audit_table_suffix: _history
      hibernate.jdbc.time_zone: Asia/Kolkata
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      batch.size: 16384
      linger.ms: 10
    consumer:
      group-id:
        default: ${DEFAULT_GROUP_ID:default-group-id}
      max.poll.interval.ms: 300000
      heartbeat.ms: 3000
      session.timeout.ms: 45000
      max.poll.records: 500
      fetch.max.bytes: 52428800
      fetch.min.bytes: 1
      max.partition.fetch.bytes: 1048576
      concurrency:
        default: 2

management:
  endpoints:
    web.exposure.include: health,prometheus,threaddump,heapdump,metrics,loggers
    jmx.exposure.include: "*"
  health:
    redis.enabled: false
    rabbit.enabled: false
  metrics:
    enable:
      http: true
      kafka: true
      disk: true
      system: true
      cache: true
      spring.data.repository: true
      logback.events: false
      log4j2.events: false
  export:
    prometheus:
      enabled: true

server:
  port: 8081

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true
    defaultModelsExpandDepth: 0
    defaultModelExpandDepth: 0

hbase:
  zookeeper:
    quorum: localhost
    property:
      clientPort: 2181